name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  # 构建工作
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0 # 如果未启用 lastUpdated，则不需要
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.3
          cache: npm # 或 pnpm / npm
      - name: Build
        working-directory: ./
        run: | 
          echo '安装依赖'
          npm install
          echo '打包项目'
          npm run build
          echo '打包完成'
          ls -a
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          token: ${{ secrets.ACCESS_TOKEN  }}
          branch: gh-pages
          folder: dist